### ISSUE TITLE
Aliasのx64をx86、またはintelに修正する

### ISSUE THREAD

**Issue by BlueEventHorizon** [daichikuwa0618/dotfiles#7]
x86_x64の意味は、x86アーキテクチャCPUの64bit版という意味です。ですので、ここでのalias名は、x64では泣くx86またはintelが適当と思います。

**Comment by daichikuwa0618** [comment]
@BlueEventHorizon 
Issue ありがとうございます。

適当に名前付けてたのでおっしゃるとおりです！
PR にて対応下のでこちらクローズしました。

また何かあれば Open ください。
